In [1]:
import pandas as pd

In [2]:
symbols = ['aapl', 'btc', 'eth', 'spx']

In [10]:
scores = []
for symbol in symbols:
    data = pd.read_pickle('data/stocktwits/datasets_clean/' + symbol + '_twits_012018_072019_clean.pickle')
    
    data.index = pd.to_datetime(data.created_at)
    data = data.tz_convert('America/New_York')
    data = data[data.index > pd.to_datetime('2018-07-01 04:00:00+00:00').tz_convert('America/New_York')]
    
    data = data.groupby(data.index.date).count()
    data['pred'] = data.created_at
    
    prices = pd.read_csv('data/prices/' + symbol + '_prices.csv', header=None, index_col=0)
    prices.index = pd.to_datetime(prices.index)
    
    data = data[['pred']].join(prices, how='inner')
    data[['pred']].to_csv('data/pred/pred_stw_vol_brt_' + symbol + '.csv')

In [11]:
data

            pred        1
2018-07-02   321  2726.71
2018-07-03   233  2713.22
2018-07-05   351  2736.61
2018-07-06   330  2759.82
2018-07-09   365  2784.17
2018-07-10   420  2793.84
2018-07-11   367  2774.02
2018-07-12   401  2798.29
2018-07-13   280  2801.31
2018-07-16   313  2798.43
2018-07-17   342  2809.55
2018-07-18   287  2815.62
2018-07-19   296  2804.49
2018-07-20   295  2801.83
2018-07-23   282  2806.98
2018-07-24   333  2820.40
2018-07-25   408  2846.07
2018-07-26   265  2837.44
2018-07-27   360  2818.82
2018-07-30   309  2802.60
2018-07-31   318  2816.29
2018-08-01   345  2813.36
2018-08-02   315  2827.22
2018-08-03   289  2840.35
2018-08-06   350  2850.40
2018-08-07   322  2858.45
2018-08-08   320  2857.70
2018-08-09   310  2853.58
2018-08-10   400  2833.28
2018-08-13   380  2821.93
...          ...      ...
2019-06-19   345  2926.46
2019-06-20   405  2954.18
2019-06-21   244  2950.46
2019-06-24   247  2945.35
2019-06-25   323  2917.38
2019-06-26   268  2913.78
2019-06-27   207  2924.92
2019-06-28   222  2941.76
2019-07-01   307  2964.33
2019-07-02   261  2973.01
2019-07-03   342  2995.82
2019-07-05   226  2990.41
2019-07-08   228  2975.95
2019-07-09   255  2979.63
2019-07-10   345  2993.07
2019-07-11   380  2999.91
2019-07-12   361  3013.77
2019-07-15   252  3014.30
2019-07-16   268  3004.04
2019-07-17   302  2984.42
2019-07-18   248  2995.11
2019-07-19   248  2976.61
2019-07-22   213  2985.03
2019-07-23   269  3005.47
2019-07-24   254  3019.56
2019-07-25   223  3003.67
2019-07-26   237  3025.86
2019-07-29   180  3020.97
2019-07-30   219  3013.18
2019-07-31   377  2980.38

[272 rows x 2 columns]